### PR TITLE
Upgrade node-foursquare to 0.4.5. Closes #888

### LINKED ISSUE #888: Fix Foursquare integration
Upgrading node-foursquare from 0.3.3 to 0.4.3 in package.json breaks the project:

```
$ npm start

> hackathon-starter@5.1.2 start /mnt/c/temp/hackathon-starter
> node app.js

/mnt/c/temp/hackathon-starter/controllers/api.js:16
const { Venues, Users } = require('node-foursquare')({
                                                    ^

TypeError: require(...) is not a function
    at Object.<anonymous> (/mnt/c/temp/hackathon-starter/controllers/api.js:16:53)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/mnt/c/temp/hackathon-starter/app.js:35:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
```

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- library update
- babel-polyfill added:
https://babeljs.io/docs/en/babel-polyfill/

At the moment, the `babel-polyfill` is required to be included in the project config.

Please wait for input from `node-foursquare` project:
https://github.com/clintandrewhall/node-foursquare/issues/37#issuecomment-415827506

### CODE REVIEW

**Comment by YasharF** [comment]
Why is bable poly fill required?  This seems lto be an issue in node-foursquare that needs to be addressed in that library to avoid bloating the consumers.

**Comment by clintandrewhall** [comment]
This is fixed in the latest version, which I published yesterday. Should be g2g.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by peterblazejewicz** [comment]
@clintandrewhall Thanks!
@YasharF updated to be focused update

**Comment by YasharF** [comment]
@peterblazejewicz 
When I try to load /api/foursquare the server crashes with a 500 code.  Are you getting a different result when testing?

```
/mnt/c/temp/hackathon-starter$ npm start

> hackathon-starter@5.1.1 start /mnt/c/temp/hackathon-starter
> node app.js

✓ App is running at http://localhost:8080 in development mode
  Press CTRL-C to stop

(node:119) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
GET / 200 1595.825 ms - -
GET /js/lib/jquery.min.js 200 32.677 ms - -
GET /js/lib/bootstrap.min.js 200 15.802 ms - -
GET /js/lib/popper.min.js 200 18.405 ms - -
GET /js/main.js 200 20.531 ms - 100
GET /webfonts/fa-solid-900.woff2 200 5.904 ms - 68948
GET /api 200 301.343 ms - -
TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function. Received type undefined
    at promisify (internal/util.js:257:11)
    at exports.getFoursquare (/mnt/c/temp/hackathon-starter/controllers/api.js:45:30)
    at Layer.handle [as handle_request] (/mnt/c/temp/hackathon-starter/node_modules/express/lib/router/layer.js:95:5)
    at next (/mnt/c/temp/hackathon-starter/node_modules/express/lib/router/route.js:137:13)
    at exports.isAuthorized (/mnt/c/temp/hackathon-starter/config/passport.js:551:5)
    at Layer.handle [as handle_request] (/mnt/c/temp/hackathon-starter/node_modules/express/lib/router/layer.js:95:5)
    at next (/mnt/c/temp/hackathon-starter/node_modules/express/lib/router/route.js:137:13)
    at exports.isAuthenticated (/mnt/c/temp/hackathon-starter/config/passport.js:539:12)
    at Layer.handle [as handle_request] (/mnt/c/temp/hackathon-starter/node_modules/express/lib/router/layer.js:95:5)
    at next (/mnt/c/temp/hackathon-starter/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/mnt/c/temp/hackathon-starter/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/mnt/c/temp/hackathon-starter/node_modules/express/lib/router/layer.js:95:5)
    at /mnt/c/temp/hackathon-starter/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/mnt/c/temp/hackathon-starter/node_modules/express/lib/router/index.js:335:12)
    at next (/mnt/c/temp/hackathon-starter/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/mnt/c/temp/hackathon-starter/node_modules/serve-static/index.js:121:7)
GET /api/foursquare 500 21.551 ms - -
GET /favicon.ico 404 5.993 ms - 150

```

**Comment by peterblazejewicz** [comment]
yup,
```bash
➜  hackathon-starter git:(feat/888) ✗ npm start

> hackathon-starter@5.1.1 start /Users/piotrblazejewicz/git/hackathon-starter
> node app.js

✓ App is running at http://localhost:8080 in development mode
  Press CTRL-C to stop

GET / 200 594.443 ms - -
GET /js/lib/jquery.min.js 200 14.533 ms - -
GET /js/lib/bootstrap.min.js 200 12.318 ms - -
GET /js/main.js 200 13.830 ms - 100
GET /js/lib/popper.min.js 200 15.760 ms - -
GET /webfonts/fa-solid-900.woff2 200 5.737 ms - 62472
GET /api 200 220.293 ms - -
GET /css/main.css 200 6.198 ms - -
GET /contact 200 120.219 ms - -
GET /webfonts/fa-regular-400.woff2 200 5.318 ms - 14888
```
let me try with cache cleanup

**Comment by peterblazejewicz** [comment]
```bash
 hackathon-starter git:(feat/888) ✗ npm start

> hackathon-starter@5.1.1 start /Users/piotrblazejewicz/git/hackathon-starter
> node app.js

✓ App is running at http://localhost:8080 in development mode
  Press CTRL-C to stop

GET / 200 537.505 ms - -
^C%                                                                                                                                                           ➜  hackathon-starter git:(feat/888) ✗ npm --version
5.6.0
➜  hackathon-starter git:(feat/888) ✗ node --version
v9.3.0
```
Tested also on Node 10.6.0 (system one on Mac OS)

**Comment by YasharF** [comment]
When you are stating that you tested, are you loading the server and visiting http://localhost:8080/api/foursquare to make sure that api example page is loading and rendering fine?

**Comment by YasharF** [comment]
For testing, you need to do the full pipeline to make sure in addition to the authorization the data is being passed when API calls are made and parsed as they were intended.  There is a section in the readme for obtaining an app key from foursquare.

**Comment by peterblazejewicz** [comment]
As said, that's not a problem with obtaining api or using OAuth, the problem is that contract in `node-foursquare` changed and I've never used it before. The code in starter fails on callback from auth server with token when accessing the NF api methds, which expects different signatures. I'll probably look into that in other PR
Thanks!

**Pull request closed without merging**
