### PR TITLE
Change drop down menu to show correct formatting

### PR DESCRIPTION
**Pull request by jonasroslund**

### CODE REVIEW

**Comment by YasharF** [comment]
Can you please post before and after screenshots in different screen widths?

**Comment by jonasroslund** [comment]
Using Simplex theme from Bootswatch
[https://bootswatch.com/simplex/](https://bootswatch.com/simplex/)

**Before**

No hover:
image

Hover outside text:
image

Hover on text:
image

Narrow screen:
image

**After**

image
image
image
image

**Comment by YasharF** [comment]
I can't produce the same screenshots because of the bug mentioned at https://github.com/sahat/hackathon-starter/issues/853#issuecomment-475934766.  Do you mind sharing what you did to fix that issue?

**Comment by jonasroslund** [comment]
In those specific screenshots, I use the Simplex theme from Bootswatch together with
`.navbar-dark.bg-primary`
instead of 
`.navbar-light`
as the first line in header.pug. My complete first line is:
`.navbar.fixed-top.navbar-expand-md.navbar-dark.bg-primary`
In the default template used, the graphical error I have corrected does not show, because background colors are not used.

If you want to reproduce my screenshots above, I can propose supplementary changes. However, those supplementary changes is not needed in the master branch unless you alse want to change the theme.

Please tell me how you would like to proceed.

**Comment by peterblazejewicz** [comment]
@jonasroslund 
FYI: I've created #1014 and #1015 to fix both problems (rendering problems with navbar and switching custom themes from Bootswatch)

**Comment by YasharF** [comment]
Thank you!

**Pull request merged**
