### PR TITLE
- added get shit done by creative tim as a theme.

### PR DESCRIPTION
**Pull request by conacelelena**

### CODE REVIEW

**Comment by YasharF** [comment]
Why?  Also why a framework that has profanity in its name?  It can be somewhat of a turn off for judges that go through code during a hackathon to see profanity, and as indication of lack of professionalism.

**Comment by YasharF** [comment]
Actually, this gsdk is a NO-NO due to its license: http://www.creative-tim.com/license  For anything besides personal use you will need to purchase it.  Hackathon starter has the MIT license, pulling gsdk can create confusion and potential legal issues for the users of hackathon starter.  Even a Developer license costs $19.

**Comment by sahat** [comment]
@conacelelena @YasharF I spoke to Alex a while ago, co-founder of Creative Tim about a potential collaboration to add new themes to Hackathon Starter. I am not against that idea at all. For licensing, I am sure we can figure something out. The way it would work, only free themes would be included, and if users need additional components, they'd purchase the "Pro" version of that theme directly from www.creative-tim.com.

The main challenge right now is consistent markup across multiple themes. Ideally, you should be able to swap themes without having to make any changes to the templates, similar to how `default`, `flat-ui`, and `ios` themes currently work in Hackathon Starter. I'll ping Alex again to see if there has been any progress towards a unified markup for Creative Tim's themes.

**Comment by sahat** [comment]
@YasharF I don't think your profanity argument is a valid one. "Get shit done" is practically a motto of hackathons. In any case, it's just a theme name. If naming is such a turn off, it could be referenced as `gsd` or `gdsk` internally in Hackathon Starter.

**Comment by YasharF** [comment]
Besides the license, there is still the issue of use of profanity in the name of the project.  They are welcome to rebrand their project.  Also note the git commit message; merging this pull request at the minimum will cause a profanity to show up in the git commit log.  Very unprofessional and not cool.


> For licensing, I am sure we can figure something out. 

If they have such a thing as a free to use like under MIT license, then they should publish the MIT licensed code somewhere first.  https://github.com/timcreative/get-shit-done says "free" but it lacks a license file to indicate what "free" really means.  Most likely anything less than an MIT license for the "free" portion is insufficient.  I created an issue for them https://github.com/timcreative/get-shit-done/issues/7 to add a license file.

**Comment by YasharF** [comment]
> README 

People replace the readme as soon as they create their own project.  But the git commit log messages aren't something that can be changed as easily.  Same goes with stuff in the code if any.

**Comment by alexandru-paduraru** [comment]
Hi @YasharF, here is Alex, the co-founder of Creative Tim and one of the creators of Get Shit Done Kit (it was made with @conacelelena). Thank you for pointing out and for your explanations, you're right. As @sahat explained, we've been talking about a possible collaboration where our themes [GSDK](http://www.creative-tim.com/product/get-shit-done-kit), [Paper Kit](http://demos.creative-tim.com/paper-kit) and [Material Kit](http://demos.creative-tim.com/material-kit/index.html) can be some themes that are integrated with the Hackathon Starter. The main idea of this collaboration is that you and other developers who are using Hackathon Starter to have more good looking themes to choose from so you can focus on building the project and not building the design. In hackathons you need to deliver fast (how @sahat said, you need to "get shit done"). 

The idea is very simple, when we started our business, we offered our products through our website creative-tim.com and you could get a Personal License for free if you create an account, this was the business model that we had and it was working. So you get a product that was built by a team of 5 people in 3 months just by signing up, that's fair enough I think. Then we moved our products to GitHub so the guys who want to go deeper and work with them to get the code, fork contribute etc but we didn't change/add any license on GitHub because people were using the license that was obtained on our website. 

We will talk more with @sahat and see which is the best option for this collaboration. At this moment I think that making the free kits available under MIT license sounds like a good solution.

Now for the name, some people like it (26.000+ users are using it and ~1.000 paid for the PRO version), some doesn't like it, it's something personal. It also got ~450 upvotes and was trending in Product hunt: https://www.producthunt.com/posts/get-shit-done. Probably it will be simply called "GSDK Theme" if it will be integrated inside this awesome project :D

Please let us know if we can help you with any other information.

All the best,
Alex

**Comment by YasharF** [comment]
If you guys can add the MIT license and publish it somewhere (like in your github repo) with that license, and redo the commit message, pull request, and any code that has the word sh** (aka replaced with gsdk) I think that sounds like a good idea.

**Pull request closed without merging**
