### PR TITLE
Adding tests around the csfr token for signup and contact.

### PR DESCRIPTION
**Pull request by andrewmcnutt**
This PR is to help enhance the test coverage around POST requests. Currently only GET request have any test coverage.

### CODE REVIEW

**Comment by andrewmcnutt** [comment]
The tests run fine locally. However CircleCi is saying there is an 'Invalid login'. Anyone know if there are hidden vars causing this to fail on CircleCi?

**Comment by YasharF** [comment]
What is the double callback bug?
The error at https://travis-ci.org/sahat/hackathon-starter/jobs/500852709#L565 is because the mail transporter is trying to send out an email and the credentials for sendgrid in the .env.example are invalid/placeholders.

**Comment by andrewmcnutt** [comment]
Thanks for looking Yashar. In the 'it' portion of the POST test I originally had .expect(302, done). The was causing another GET to be fired. I was following [this](https://rjzaworski.com/2015/02/testing-around-csrf-protection) example from a gentleman named Rjzaworski while setting it up. When I double checked I realized that 'done' was not part of the test. 

In terminal if done was in there I would see this:
``` 
 POST /signup
    when valid CSRF token is provided
GET /signup 200 345.755 ms - -
Warning: .end() was called twice. This is not supported in superagent
POST /signup 302 46.899 ms - 29
GET /signup 200 71.267 ms - -
      ✓ should signup a user (129ms)
superagent: double callback bug
```

With it removed I would see this:
```
POST /signup
    when valid CSRF token is provided
GET /signup 200 37.543 ms - -
POST /signup 302 46.608 ms - 29
      ✓ should signup a user (50ms)
```

**Comment by YasharF** [comment]
@andrewmcnutt any luck with these test?

**Comment by andrewmcnutt** [comment]
@YasharF I have not gotten further with these tests.

**Comment by YasharF** [comment]
Closing this PR for now.  Feel free to reopen or submit a new one when the issues are resolved.

**Pull request closed without merging**
