### PR TITLE
Env generator shell script

### PR DESCRIPTION
**Pull request by nhuzaa**
Created a simple shell script to generate the .env file

### CODE REVIEW

**Comment by nhuzaa** [comment]
@YasharF  I am not trying to spam your repo Can you please remove the spam label as it is affecting my hacktoberfest status . You can label is any other. Will try to have quality PR later on

**Comment by YasharF** [comment]
Please do not submit PRs that are NOT needed.

Hacktoberfest is a great event to get dev involved in open source. However, it also causes a lot of people to just submit PRs to repos in hope of getting credit for hacktoberfest. These PRs are mostly spam because they are not needed. Spam by definition is any kind of unwanted or unsolicited digital communication or submission.  Looking at this PR, it is just a few lines to copy a file that we don't need.  If you are trying to figure out what the project needs and have not been using the project already, I would suggest going over the github Issues or creating a github issue.  Thanks

**Comment by nhuzaa** [comment]
@YasharF  I understand what you mean. Sorry for the inconvenience caused. Could you just close and PR and remove the label invalid and spam It would help me a lot since I am marked as spam

**Comment by nhuzaa** [comment]
@YasharF  Could you please do me a favor and remove SPAM tag to this PR. I am restricted form participating in hacktoberfest this year too because of this.

**Pull request closed without merging**
