### PR TITLE
Update README.md with new twitter logo

### PR DESCRIPTION
**Pull request by aslezar**
Updated Read Me with the new updated logo of twitter.

### CODE REVIEW

**Comment by YasharF** [comment]
Also, while you are at it, can you also go thru the readme.md and replace the word "twitter" with "X (twitter)" everywhere in that file?

**Comment by aslezar** [comment]
> Also, while you are at it, can you also go thru the readme.md and replace the word "Twitter" with "X (Twitter)" everywhere in that file?

Yeah, sure!
I have made the required changes.

**Comment by aslezar** [comment]
> Also, while you are at it, can you also go thru the readme.md and replace the word "Twitter" with "X (Twitter)" everywhere in that file?

Yeah, sure!
I have made the required changes.

**Comment by YasharF** [comment]
Let's set it as upper case (Twitter) instead of (twitter).  I made a couple of comments in-line as well.

**Comment by aslezar** [comment]
> Let's set it as upper case (Twitter) instead of (twitter). I made a couple of comments in-line as well.

Replaced twitter with Twitter.

I couldn't find any in-line comments that mention the word 'twitter'. If you're referring to the API routes or links like this one <a href="https://apps.twitter.com//" target="_blank">https://apps.twitter.com</a>, I haven't changed them as it would affect functionality."

**Comment by YasharF** [comment]
Look at the PR in github, I commented the PR

**Comment by aslezar** [comment]
Hey, thanks for your time, but I didn't quite understand what you're talking about. It would be great if you could elaborate a bit, if possible. 😅

**Comment by YasharF** [comment]
@aslezar 
image

**Comment by aslezar** [comment]
> @aslezar image

Thanks for the help!
I have made the requested changes.

**Comment by YasharF** [comment]
The logo completely disappears in dark mode 
image

**Comment by aslezar** [comment]
I have updated it with the jpg image, it will render now correctly in dark mode.

**Comment by YasharF** [comment]
Thank you!

**Pull request merged**
