### PR TITLE
add travis

### PR DESCRIPTION
**Pull request by nacimgoura**
Allows you to run tests on every deployment and ensure everything is working properly.

The github project must be connected to travis in order for it to perform the tests. It's free for open source projects.

### CODE REVIEW

**Comment by YasharF** [comment]
Travis was removed previously as part of https://github.com/sahat/hackathon-starter/commit/2a102dd5587f7a195d1a6c9efd1fd9600e271528 by @sahat  .  I don't know what the reasoning behind it was.

**Comment by nacimgoura** [comment]
OK, I didn't see :sweat_smile:

**Comment by YasharF** [comment]
Right now, there is effort involved from my end to test most pull request before merging.  Having Travis integration with github could help by having some of the checks done automatically.  Going to merge this PR; if we end up with problems later, we'll figure out what to do then.

**Comment by nacimgoura** [comment]
we should also add more tests to check all available APIs.

**Pull request merged**
