### PR TITLE
README image updates

### PR DESCRIPTION
**Pull request by nick-w-nick**
**EDIT:** I am making this PR as part of the currently ongoing Hacktoberfest 2020 event.

I have updated a majority of the images/logos/icons within the README.md file.

All low-quality, outdated, and incorrectly sized images have been replaced.

I also cloned the repo + launched the app without making any changes and took new screenshots for the prereq section of the README, as each of them seemed to previously be in different browsers, at varying sizes and quality. They were also not up to date with the current state of the repo.

I searched for valid and verified copies of each of the replaced logos/icons, and manually resized/updated each of them.

I decided to just use Imgur as my hosting platform, rather than directly storing them in the project so that it wouldn't take up unnecessary space in the repo when it is cloned.

All of the logos/icons are stored in this Imgur gallery post if needed.
https://imgur.com/a/0vnnP7c

Please let me know if any further changes or modifications need to be made to the images in this PR.

Thanks!

### CODE REVIEW

**Comment by YasharF** [comment]
Marking as SPAM.  Please note that submitting unnecessary PRs are not acceptable for Hacktoberfest and are disqualified.  This is also noted on Hacktoberfest's website.

**Comment by nick-w-nick** [comment]
Hello @YasharF , would you mind taking another look at this PR? I spent over three hours manually creating custom images and updating them to work properly within the README. Could you clone this PR and then open it in a markdown preview inside your editor? I used the [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) VSCode extension.

I honestly would deem this PR as absolutely necessary, as it updates the example screenshots, which are quite out of date and aren't of the best quality.

I would really appreciate a second look at this.

You can keep it as spam if you want, I was doing it as part of Hacktoberfest, but even if I can't get credit for it, I really believe it is a useful PR that would benefit the repository.

Let me know if you need any further clarification on these changes before you make a final judgment.

Thank you very much for your time and effort in managing this repo.

**Comment by YasharF** [comment]
Thank you for the efforts, however, the PR is not solving any known issues.  As far as Hacktoberfest goes, only https://github.com/sahat/hackathon-starter/issues marked with Hacktoberfest as well as sever bug fixes (aka 500 server errors, etc) are being accepted.

**Comment by nick-w-nick** [comment]
I agree it isn't solving any "known issues", but I would say that outdated imagery is likely to put some potential users off in terms of utilizing the repo, as well as those looking to contribute, as it makes it look like it isn't regularly maintained.

As I said, I am completely fine with keeping it marked as spam so it doesn't go towards my Hacktoberfest contributions, I just believe it's a valuable PR that anyone else is unlikely to even attempt to do.

Thank you.

**Comment by nick-w-nick** [comment]
I also forgot to note that you can just view the updates by viewing my fork of the repo.
https://github.com/nick-w-nick/hackathon-starter/tree/readme-image-updates

The preview images, prereq platform icons, and API provider logos look much better with the updates.

**Comment by nick-w-nick** [comment]
@sahat Would you mind taking a look at this PR as a second opinion?
I just want to help the repo, and believe it will benefit it positively.

To reiterate, I don't care if it goes towards my Hacktoberfest PR count, you can keep it labeled as spam, I just think it is very beneficial for the overall representation of the repository.

**Pull request closed without merging**
