### PR TITLE
Add semicolon to test/model.js

### PR DESCRIPTION
**Pull request by dok**
It was bothering me..

### CODE REVIEW

**Comment by niallobrien** [comment]
Technically it's not a syntax error as Javascript does automatic semicolon insertion.

**Comment by dok** [comment]
That's right, how could I have forgotten? I must have believed for a second since it was showing up in my linter.

Regardless, it's good practice and it will follow the same conventions as the rest of the repo.

**Comment by niallobrien** [comment]
Agreed. :+1:

**Comment by sahat** [comment]
I always put semicolons in my code, if it's not there I simply forgot. Thanks!

**Comment by sahat** [comment]
On a related topic, does anyone have experience with mocking models? Current tests rely on hitting a database (i.e. MongoDB must be running), which kind of defeats the main principle of unit testing. I just didn't know how to do it any better back then.

**Comment by dok** [comment]
Could you clarify a little bit more? From what I'm understanding, model tests should be abstracted so that model-related unit tests should not ping the database. Is that what you are implying?

**Comment by niallobrien** [comment]
https://www.npmjs.com/package/mockgoose might be worth taking a look at.

**Pull request merged**
