### PR TITLE
Changed from twitter to twitter-lite

### PR DESCRIPTION
**Pull request by KhushalPShah**
I am new to Open Source and starting my journey with hacktoberfest.
I tried solving this issue.
Issues : https://github.com/sahat/hackathon-starter/issues/1071
If there are any errors, please let me know.
Thanks!

### CODE REVIEW

**Comment by dnafication** [comment]
This currently fails with error. I am also having a look will suggest. Twitter recently removed callback url support.

```
Error: Desktop applications only support the oauth_callback value 'oob'
    at Strategy.parseErrorResponse (/Users/dna/devd/hackathon-starter/node_modules/passport-twitter/lib/strategy.js:206:12)
    at Strategy.OAuthStrategy._createOAuthError (/Users/dna/devd/hackathon-starter/node_modules/passport-oauth1/lib/strategy.js:393:16)
    at /Users/dna/devd/hackathon-starter/node_modules/passport-oauth1/lib/strategy.js:244:41
    at /Users/dna/devd/hackathon-starter/node_modules/oauth/lib/oauth.js:543:17
    at passBackControl (/Users/dna/devd/hackathon-starter/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/Users/dna/devd/hackathon-starter/node_modules/oauth/lib/oauth.js:409:9)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by KhushalPShah** [comment]
Did you try specifying the callback_url on the twitter developer app settings?
Specifying http://127.0.0.1 should ideally work.

**Comment by dnafication** [comment]
My bad it works now. I tried with localhost but it didn't work. Using ngrok seems to be working fine. Twitter is asking for details like website, terms and privacy policy urls. I guess its a security thing.

**Comment by YasharF** [comment]
Deploying this patch results in a 500 error when loading /api/twitter

```
2020-10-07T18:07:14.195446+00:00 heroku[router]: at=info method=GET path="/api/twitter" host=hackathon-starter.walcony.com request_id=a055xxxxxxxxxxxxxxxxxxxxxxx1262 fwd="26xxxxxxxxxxxxxxxxxxxx" dyno=web.1 connect=1ms service=35ms status=302 bytes=493 protocol=http
2020-10-07T18:07:14.587511+00:00 heroku[router]: at=info method=GET path="/auth/twitter" host=hackathon-starter.walcony.com request_id=bfxxxxxxxxxxxxxxxxxxxxxx10ee fwd="26xxxxxxxxxxxxxxxxxx" dyno=web.1 connect=1ms service=272ms status=302 bytes=420 protocol=http
2020-10-07T18:07:14.587896+00:00 app[web.1]: GET /auth/twitter 302 268.849 ms - 0
2020-10-07T18:07:16.808007+00:00 heroku[router]: at=info method=GET path="/auth/twitter/callback?oauth_token=EZxxxxxxxxxxxxxxxxxg4&oauth_verifier=gAxxxxxxxxxxxxxxxxxpy" host=hackathon-starter.walcony.com request_id=5dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx2f fwd="26xxxxxxxxxxxxxxxxxxxxxxxxx" dyno=web.1 connect=0ms service=931ms status=302 bytes=490 protocol=http
2020-10-07T18:07:16.810092+00:00 app[web.1]: GET /auth/twitter/callback?oauth_token=EZxxxxxxxxxxxxxxxxg4&oauth_verifier=gAxxxxxxxxxxxxxxxxxxxxxxxpy 302 916.314 ms - 68
2020-10-07T18:07:17.053140+00:00 app[web.1]: {
2020-10-07T18:07:17.053142+00:00 app[web.1]: _headers: Headers {
2020-10-07T18:07:17.053143+00:00 app[web.1]: [Symbol(map)]: [Object: null prototype] {
2020-10-07T18:07:17.053143+00:00 app[web.1]: 'cache-control': [Array],
2020-10-07T18:07:17.053143+00:00 app[web.1]: connection: [Array],
2020-10-07T18:07:17.053144+00:00 app[web.1]: 'content-encoding': [Array],
2020-10-07T18:07:17.053144+00:00 app[web.1]: 'content-length': [Array],
2020-10-07T18:07:17.053144+00:00 app[web.1]: 'content-type': [Array],
2020-10-07T18:07:17.053145+00:00 app[web.1]: date: [Array],
2020-10-07T18:07:17.053145+00:00 app[web.1]: server: [Array],
2020-10-07T18:07:17.053146+00:00 app[web.1]: 'set-cookie': [Array],
2020-10-07T18:07:17.053147+00:00 app[web.1]: 'strict-transport-security': [Array],
2020-10-07T18:07:17.053147+00:00 app[web.1]: 'x-connection-hash': [Array],
2020-10-07T18:07:17.053148+00:00 app[web.1]: 'x-response-time': [Array]
2020-10-07T18:07:17.053148+00:00 app[web.1]: }
2020-10-07T18:07:17.053148+00:00 app[web.1]: },
2020-10-07T18:07:17.053149+00:00 app[web.1]: errors: [ { code: 89, message: 'Invalid or expired token.' } ]
2020-10-07T18:07:17.053149+00:00 app[web.1]: }
2020-10-07T18:07:17.056759+00:00 app[web.1]: GET /api/twitter 500 122.338 ms - 12
```

**Comment by YasharF** [comment]
(I'll be removing the invalid label once all the issues are resolved).  Make sure to fully test the PR and to make sure that the functionality stays the same (see https://hackathon-starter.walcony.com for the current implementation).  A few places to validate:

/account : 
Link / Unlink your Twitter account

/api/twitter : 
(need it to have the same functionality as the current implementation, make sure to test sending messages as well)

/login : 
Sign in with Twitter

Also, note that in the oAuth code, there is some logic that updates user profile name, location, and picture based on the data received from twitter.  Make sure this functionality is replicated as well.  Thanks!

**Comment by KhushalPShah** [comment]
Sure @YasharF 
I'll check these and make the changes.

Thanks for the help!

**Comment by KhushalPShah** [comment]
@YasharF 
I am getting the following Error.
Could you please help me with finding what is the issue?

image

**Comment by KhushalPShah** [comment]
Hey @YasharF 
I have made some changes in the controllers/api for the getTwitter and postTwitter functions, making it work with twitter-lite. I am able to view the tweets and also post a new tweet using the API.

Please review this.
Thanks!

**Comment by KhushalPShah** [comment]
@YasharF 
Is there any error with this?
If yes, please let me know.
Else, can you add a Hacktoberfest label to this issue? It will help me.

Thanks and Cheers!

**Comment by YasharF** [comment]
Thank you!

**Pull request merged**
