### PR TITLE
*.jade inside views/ directory renamed to *.pug

### PR DESCRIPTION
**Pull request by shubhamoli**

### CODE REVIEW

**Comment by sahat** [comment]
@shubhamoli pug 2.0 is still in beta. From your experience is it stable enough to use yet?

**Comment by shubhamoli** [comment]
OOPS! There are few syntactical differences between pug and Jade. I haven't gone through your views, but now I'm going to dig deeper and re-write all views to support pug.

**Comment by mazing** [comment]
+1

**Comment by sahat** [comment]
Looks like package.json is missing `pug` dependency.

**Comment by shubhamoli** [comment]
@sahat, yes I missed --save flag while installing pug

**Comment by sahat** [comment]
I had some issues merging this patch, so I went ahead and replaced all jade extensions to pug manually. 

It worked perfectly without changing any templates. Even though `pug` is still in beta5, I haven't run across any compatibility issues, so I am going to go ahead and switch over all extensions to pug.

**Comment by sahat** [comment]
Closed by 935f13df7c1b67f9d61ef60abc01330b1cf57756.

**Pull request closed without merging**
